# 3x-ui VPN Service configuration
services:
  3x-ui:
    image: ghcr.io/mhsanaei/3x-ui:latest
    container_name: 3x-ui
    restart: unless-stopped
    ports:
      - 54321:54321  # Admin panel
      # Re-enable direct access to VPN service
      - 2053:2053    # VPN panel custom port
      # Add any other ports your VPN protocols require
      # - port:port
    volumes:
      # Mount the db directory for persistence
      - ./db:/etc/x-ui
      # Mount certificates directory
      - ./cert:/root/cert
      # Mount logs directory
      - ./logs:/var/log/x-ui
    environment:
      - XRAY_VMESS_AEAD_FORCED=false
      - PANEL_PATH=BXv8SI7gBe     # Set custom panel path
      # Set custom base URL for assets without port number
      - BASE_URL=http://localhost
      # Force using assets from BASE_URL without port
      - ASSETS_OVERRIDE=true
      # Run in secure mode to enforce HTTPS (disabled for local dev)
      - XUI_ENFORCE_HTTPS=false
    # Removing the health check as the container doesn't have the necessary commands
    # Will rely on process monitoring instead
    networks:
      - vpn-network

networks:
  vpn-network:
    driver: bridge

# If you want to use named volumes instead of local bind mounts
# volumes:
#   x-ui-data:
#     driver: local 