# 3x-ui VPN Service configuration
services:
  3x-ui:
    image: ghcr.io/mhsanaei/3x-ui:latest
    container_name: 3x-ui
    restart: unless-stopped
    ports:
      # Admin panel port - expose directly
      - 2053:2053  # Admin panel
      # Essential XRay protocol ports
      - 443:443    # HTTPS/TLS
      - 80:80      # HTTP
      # Additional VPN protocol ports
      - 54321:54321 # Fallback/additional port
    volumes:
      # Mount the db directory for persistence
      - ./db:/etc/x-ui
      # Mount certificates directory
      - ./cert:/root/cert
      # Mount logs directory
      - ./logs:/var/log/x-ui
    environment:
      - XRAY_VMESS_AEAD_FORCED=${XRAY_VMESS_AEAD_FORCED:-false}
      - PANEL_PATH=${PANEL_PATH:-BXv8SI7gBe}
      # Disable port in asset URLs to fix certificate issues
      - ASSETS_PATH=/BXv8SI7gBe/assets
      - SKIP_PORT_IN_URL=true
      # Set correct base URL without port
      - BASE_URL=${VPN_DOMAIN:-service.foodshare.club}
      # Don't use HTTPS for internal asset URLs
      - FORCE_HTTPS=false
      - ASSETS_OVERRIDE=true
      # Custom credentials
      - XUI_USERNAME=${XUI_USERNAME:-admin}
      - XUI_PASSWORD=${XUI_PASSWORD:-admin}
      # JWT Secret
      - JWT_SECRET=${JWT_SECRET:-change_me_in_production}
      # Domain information
      - VPN_DOMAIN=${VPN_DOMAIN:-service.foodshare.club}
      - ADMIN_EMAIL=${ADMIN_EMAIL:-admin@example.com}
    networks:
      - vpn-network

networks:
  vpn-network:
    driver: bridge

# If you want to use named volumes instead of local bind mounts
# volumes:
#   x-ui-data:
#     driver: local 