version: '3.8'

# 3x-ui VPN Service configuration
services:
  3x-ui:
    image: ghcr.io/mhsanaei/3x-ui:latest
    container_name: 3x-ui
    restart: unless-stopped
    ports:
      - 54321:54321  # Admin panel
      # Don't expose 2053 directly to the internet
      # Instead route all traffic through Caddy
      # - 2053:2053    # VPN panel custom port
      # Add any other ports your VPN protocols require
      # - port:port
    volumes:
      # Mount the db directory for persistence
      - ./db:/etc/x-ui
      # Mount certificates directory
      - ./cert:/root/cert
      # Mount logs directory
      - ./logs:/var/log/x-ui
    environment:
      - XRAY_VMESS_AEAD_FORCED=false
      - PANEL_PATH=BXv8SI7gBe     # Set custom panel path
      # Set custom base URL for assets without port number
      - BASE_URL=https://service.foodshare.club
      # Force using assets from BASE_URL without port
      - ASSETS_OVERRIDE=true
      # Run in secure mode to enforce HTTPS
      - XUI_ENFORCE_HTTPS=true
    healthcheck:
      test: [CMD, curl, -f, http://localhost:54321/login]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - web
      - no-zero-trust-cloudflared
    labels:
      - caddy=service.foodshare.club
      - caddy.reverse_proxy=/BXv8SI7gBe*

networks:
  web:
    external: true
  no-zero-trust-cloudflared:
    external: true

# If you want to use named volumes instead of local bind mounts
# volumes:
#   x-ui-data:
#     driver: local 