# 3x-ui VPN Service configuration
services:
  3x-ui:
    image: ghcr.io/mhsanaei/3x-ui:latest
    container_name: 3x-ui
    restart: unless-stopped
    ports:
      # Important: The admin panel actually runs on port 2053 inside the container
      # We map it to 54321 on the host for access via https://localhost:54321/BXv8SI7gBe/
      - 54321:2053  # Map container's 2053 port to host's 54321
    volumes:
      # Mount the db directory for persistence
      - ./db:/etc/x-ui
      # Mount certificates directory
      - ./cert:/root/cert
      # Mount logs directory
      - ./logs:/var/log/x-ui
    environment:
      - XRAY_VMESS_AEAD_FORCED=false
      - PANEL_PATH=BXv8SI7gBe     # Custom panel path - access via /BXv8SI7gBe/
      # Set custom base URL for assets without port number
      - BASE_URL=http://localhost
      # Force using assets from BASE_URL without port
      - ASSETS_OVERRIDE=true
      # Force using HTTP instead of HTTPS for local development
      - XUI_ENFORCE_HTTPS=false
      # Disable all TLS (though the panel still uses HTTPS internally)
      - FORCE_HTTPS=false
      - DISABLE_TLS=true
      # Set proper URL protocol
      - URL_PROTOCOL=http
    # Removing the health check as the container doesn't have the necessary commands
    # Will rely on process monitoring instead
    networks:
      - vpn-network

networks:
  vpn-network:
    driver: bridge

# If you want to use named volumes instead of local bind mounts
# volumes:
#   x-ui-data:
#     driver: local 