# 3x-ui VPN Service configuration
services:
  3x-ui:
    image: ghcr.io/mhsanaei/3x-ui:latest
    container_name: 3x-ui
    restart: unless-stopped
    ports:
      # Important: The admin panel runs on port 2053 inside the container
      # We map it to 2053 on the host for access via http://localhost:2053/BXv8SI7gBe/
      - "${HTTPS_PORT}:2053"  # Map container's 2053 port to host's 2053
    volumes:
      # Mount the db directory for persistence
      - ./db:/etc/x-ui
      # Mount certificates directory
      - ./cert:/root/cert
      # Mount logs directory
      - ./logs:/var/log/x-ui
    environment:
      - XRAY_VMESS_AEAD_FORCED=${XRAY_VMESS_AEAD_FORCED}
      - PANEL_PATH=${PANEL_PATH}
      # Set custom base URL for assets
      - BASE_URL=http://${VPN_DOMAIN}
      # Force using assets from BASE_URL without port
      - ASSETS_OVERRIDE=true
      # Use HTTP for local development
      - XUI_ENFORCE_HTTPS=false
      - FORCE_HTTPS=false
      - DISABLE_TLS=true
      # Set proper URL protocol
      - URL_PROTOCOL=http
      # Custom credentials
      - XUI_USERNAME=${XUI_USERNAME}
      - XUI_PASSWORD=${XUI_PASSWORD}
      # JWT Secret
      - JWT_SECRET=${JWT_SECRET}
      # Domain information
      - VPN_DOMAIN=${VPN_DOMAIN}
      - ADMIN_EMAIL=${ADMIN_EMAIL}
    # Removing the health check as the container doesn't have the necessary commands
    # Will rely on process monitoring instead
    networks:
      - vpn-network

networks:
  vpn-network:
    driver: bridge

# If you want to use named volumes instead of local bind mounts
# volumes:
#   x-ui-data:
#     driver: local 