#!/bin/bash
# This script generates a .env file from GitHub secrets during deployment

set -e

# Print status with color
print_status() {
  local color=$1
  local message=$2
  
  # Colors
  local RED='\033[0;31m'
  local GREEN='\033[0;32m'
  local YELLOW='\033[1;33m'
  local BLUE='\033[0;34m'
  local NC='\033[0m' # No Color
  
  case $color in
    "red") echo -e "${RED}${message}${NC}" ;;
    "green") echo -e "${GREEN}${message}${NC}" ;;
    "yellow") echo -e "${YELLOW}${message}${NC}" ;;
    "blue") echo -e "${BLUE}${message}${NC}" ;;
    *) echo "${message}" ;;
  esac
}

# Get script directory
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
REPO_DIR="$(dirname "${SCRIPT_DIR}")"

# Define .env file path
ENV_FILE="${REPO_DIR}/.env"

print_status "blue" "==== Generating .env file from GitHub secrets ===="

# Create or overwrite .env file
> "${ENV_FILE}"

# Add environment variables
{
  echo "# 3x-ui VPN Service Configuration"
  echo "# Generated by CI/CD on $(date)"
  echo ""
  echo "# Panel Path - The secure path for accessing the admin panel"
  echo "PANEL_PATH=${PANEL_PATH:-BXv8SI7gBe}"
  echo ""
  echo "# HTTPS Port - Port for accessing the admin interface"
  echo "HTTPS_PORT=${HTTPS_PORT:-2053}"
  echo ""
  echo "# VPN Domain - The domain name for your VPN service"
  echo "VPN_DOMAIN=${VPN_DOMAIN:-service.foodshare.club}"
  echo ""
  echo "# Admin Email - Email address for certificate notifications"
  echo "ADMIN_EMAIL=${ADMIN_EMAIL:-admin@example.com}"
  echo ""
  echo "# XRay Configuration"
  echo "XRAY_VMESS_AEAD_FORCED=${XRAY_VMESS_AEAD_FORCED:-false}"
  echo ""
  echo "# Admin Credentials"
  echo "XUI_USERNAME=${XUI_USERNAME:-admin}"
  echo "XUI_PASSWORD=${XUI_PASSWORD:-admin}"
  echo ""
  echo "# JWT Secret - Used for authentication"
  echo "JWT_SECRET=${JWT_SECRET:-change_me_in_production}"
} >> "${ENV_FILE}"

# Set proper permissions
chmod 600 "${ENV_FILE}"

print_status "green" "✅ .env file generated successfully at ${ENV_FILE}"
print_status "yellow" "⚠️ Make sure to verify these values are correct in your GitHub secrets"

# Print .env file for debugging (without showing sensitive information)
print_status "blue" "==== .env file contents (secrets masked) ===="
sed 's/\(XUI_PASSWORD=\).*/\1******/; s/\(JWT_SECRET=\).*/\1******/' "${ENV_FILE}" 